In [1]:
import torch

In [2]:
import numpy as np

In [4]:
print(torch.__version__)

1.9.1+cpu


In [9]:
arr=np.array([1,2,3,4,5])

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr.dtype

dtype('int32')

In [12]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [14]:
x=torch.from_numpy(arr)

In [15]:
type(x)

torch.Tensor

In [16]:
x.dtype

torch.int32

In [17]:
TT=torch.as_tensor(arr)

In [18]:
TT.dtype

torch.int32

In [19]:
array2D=np.arange(0.0,12.0)

In [23]:
array2D=array2D.reshape(4,3)

In [24]:
array2D

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [26]:
X2=torch.from_numpy(array2D)

In [28]:
X2.dtype

torch.float64

In [29]:
type(X2)

torch.Tensor

In [30]:
X2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [31]:
torch.empty(4,5)

tensor([[9.0919e-39, 9.2755e-39, 2.9389e-39, 1.0286e-38, 1.0469e-38],
        [1.0653e-38, 1.0194e-38, 2.9389e-39, 1.0194e-38, 9.9184e-39],
        [2.9389e-39, 1.0194e-38, 2.9389e-39, 9.2755e-39, 9.0918e-39],
        [1.0010e-38, 9.9184e-39, 1.0653e-38, 9.1837e-39, 9.6428e-39]])

In [33]:
A1=torch.tensor(np.arange(5))
A1

tensor([0, 1, 2, 3, 4], dtype=torch.int32)

In [34]:
A2=torch.Tensor(np.arange(5))
A2

tensor([0., 1., 2., 3., 4.])

In [35]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [37]:
torch.zeros(4,3,dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [38]:
torch.ones(4,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [39]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [40]:
torch.arange(0,18,2).reshape(3,-1)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [41]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [42]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [43]:
X=torch.tensor([1,2,3])

In [44]:
X.dtype

torch.int64

In [46]:
X.type(torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [48]:
X.type(torch.float32)

tensor([1., 2., 3.])

In [49]:
torch.rand(4,3)

tensor([[0.9644, 0.7177, 0.0415],
        [0.0035, 0.5115, 0.9405],
        [0.7789, 0.0403, 0.0748],
        [0.7982, 0.6214, 0.2649]])

In [51]:
torch.randn(6,5)

tensor([[ 2.1106,  0.6960, -0.9668, -0.0082,  0.1029],
        [-0.1269,  1.5113, -0.7965, -0.8862, -0.0539],
        [-0.0970,  1.3565, -1.2046,  0.0989,  1.1572],
        [ 1.6275, -2.6093,  0.4964,  0.6754, -0.5015],
        [-1.3077, -0.9878,  0.1760,  0.1895,  1.0312],
        [ 0.2282, -0.4753,  0.3672,  0.6291, -0.6952]])

In [65]:
torch.randint(low=4,high=10,size=(4,4))

tensor([[7, 9, 9, 6],
        [9, 6, 5, 7],
        [6, 6, 4, 6],
        [5, 9, 5, 4]])

In [66]:
Z=torch.zeros(2,4)

In [72]:
Z1=torch.rand_like(Z)
Z1

tensor([[0.4642, 0.3347, 0.3225, 0.1773],
        [0.9393, 0.2076, 0.9617, 0.2238]])

In [71]:
Z2=torch.randn_like(Z)
Z2

tensor([[-0.2869,  1.6893, -0.4066, -0.4073],
        [-0.1593,  1.1097, -0.3607, -0.1169]])

In [78]:
torch.manual_seed(42)

In [79]:
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [80]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [81]:
X=torch.arange(6).reshape(2,3)

In [82]:
X

tensor([[0, 1, 2],
        [3, 4, 5]])

In [85]:
X[1,2]

tensor(5)

In [86]:
X[0,0]

tensor(0)

In [87]:
X[1,1]

tensor(4)

In [88]:
X[:,:]

tensor([[0, 1, 2],
        [3, 4, 5]])